
version: "3.10"

services:
  postgres_container:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: 'stylenest'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1999'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    container_name: stylenest_container
    ports:
      - 8000:8000
    image: app:stylenest
    command: bash -c "apt-get update && apt-get install -y postgresql-client && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres_container

volumes:
  postgres_data:
