# Generated by Django 5.0.2 on 2024-02-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('C_description', models.TextField(blank=True)),
                ('C_image', models.ImageField(blank=True, upload_to='category/')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('C_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Pro_description', models.TextField(blank=True)),
                ('Pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pro_stock', models.IntegerField()),
                ('Pro_avalabile', models.BooleanField(default=True)),
                ('Pro_created', models.DateTimeField(auto_now_add=True)),
                ('pro_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_home.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('Pro_name',),
            },
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_image', models.ImageField(upload_to='Product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_home.product')),
            ],
        ),
    ]
