# Generated by Django 5.0.2 on 2024-02-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pro_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
