# Generated by Django 5.0.2 on 2024-02-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Pro_avalabile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Pro_stock',
        ),
    ]
