# Generated by Django 5.0.2 on 2024-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0004_alter_category_c_name_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
