# Generated by Django 5.0.2 on 2024-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0005_category_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
