# Generated by Django 5.0.2 on 2024-02-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0007_alter_category_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='Admin_home.category'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Admin_home.product'),
        ),
    ]
