# Generated by Django 5.0.2 on 2024-02-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0012_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pro_offer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
