# Generated by Django 5.0.2 on 2024-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0013_product_pro_offer_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Cate_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pro_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
