# Generated by Django 5.0.2 on 2024-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0014_category_cate_offer_alter_product_pro_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Cate_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='Cate_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
