# Generated by Django 5.0.2 on 2024-03-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0016_remove_product_cate_offer_category_cate_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='C_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
