# Generated by Django 5.0.2 on 2024-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0019_alter_category_cate_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Cate_offer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
