# Generated by Django 5.0.2 on 2024-04-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0021_alter_category_cate_offer_alter_product_pro_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('header', models.CharField(max_length=100)),
                ('is_listed', models.BooleanField(default=False)),
            ],
        ),
    ]
