# Generated by Django 5.0.2 on 2024-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0022_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Cate_offer',
            field=models.IntegerField(default=0),
        ),
    ]
