# Generated by Django 5.0.2 on 2024-05-05 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0023_alter_category_cate_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='Pro_image',
            field=models.ImageField(upload_to='Product_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
