# Generated by Django 5.0.2 on 2024-03-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
