# Generated by Django 5.0.2 on 2024-03-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_remove_address_name_address_compony_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='compony_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lastst_name',
            new_name='last_name',
        ),
    ]
