# Generated by Django 5.0.2 on 2024-03-04 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_wishlist_product_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customuser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
