# Generated by Django 5.0.2 on 2024-03-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='cart_quantity',
        ),
    ]
