# Generated by Django 5.0.2 on 2024-04-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_home', '0021_alter_category_cate_offer_alter_product_pro_offer'),
        ('Cart', '0006_rename_quantity_cart_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_home.category'),
        ),
    ]
