# Generated by Django 5.0.2 on 2024-04-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_cart_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category',
            new_name='categorye',
        ),
    ]
