# Generated by Django 5.0.2 on 2024-03-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='quantity',
            new_name='ord_quantity',
        ),
    ]
