# Generated by Django 5.0.2 on 2024-03-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0002_rename_quantity_order_item_ord_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='product',
            new_name='ord_product',
        ),
    ]
