# Generated by Django 5.0.2 on 2024-03-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0003_rename_product_order_item_ord_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
    ]
