# Generated by Django 5.0.2 on 2024-03-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0004_rename_address_order_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='status',
            field=models.CharField(default='Order confirmed', max_length=20),
        ),
    ]
