# Generated by Django 5.0.2 on 2024-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0008_alter_order_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status_change_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
