# Generated by Django 5.0.2 on 2024-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_listed',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
