# Generated by Django 5.0.2 on 2024-02-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_remove_customuser_is_listed_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
