# Generated by Django 5.0.2 on 2024-02-15 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_join',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
