# Generated by Django 5.0.2 on 2024-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_customuser_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
