# Generated by Django 5.0.2 on 2024-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0010_alter_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_join',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
